import type { EpisodePlan } from "../../engine/domain.ts";

export function commercialFixturePlan(input: {
  speakers: [string, string];
  location: string;
  firstLine: string;
  duration?: number;
}): EpisodePlan {
  const [a, b] = input.speakers;
  const d = input.duration ?? 5;
  return {
    title: "You Knew",
    hook: "Three months.",
    conflict: "The lie is no longer deniable.",
    cliffhanger: "The elevator opens on someone they both know.",
    scenes: [
      {
        location: input.location,
        time: "night",
        characters: [a, b, "Nora"],
        shots: [
          {
            type: "dialogue",
            speaker: a,
            dialogue: input.firstLine,
            emotion: "controlled",
            delivery: "quiet",
            pace: "slow",
            camera: "medium close-up, conflict already in motion",
            mouth_visibility_required: true,
            duration_hint_seconds: 7,
            function: "hook_cu",
            audio_role: "onscreen",
            edit_mode: "locked_take",
            eyeline: "lens_forbidden",
          },
          {
            type: "dialogue",
            speaker: b,
            dialogue: "Don't do this here.",
            emotion: "caught",
            delivery: "quiet",
            pace: "fast",
            camera: "close-up",
            mouth_visibility_required: true,
            duration_hint_seconds: 6,
            function: "accusation_cu",
            audio_role: "onscreen",
          },
          {
            type: "reaction",
            speaker: b,
            dialogue: "Three months is a confession.",
            emotion: "listening",
            delivery: null,
            pace: null,
            camera: "listener close-up",
            mouth_visibility_required: false,
            duration_hint_seconds: 6,
            function: "listener_hold",
            audio_role: "offscreen",
            speaker_on_camera: a,
            speakers_off_camera: [b],
          },
          {
            type: "broll",
            speaker: null,
            dialogue: null,
            emotion: null,
            delivery: null,
            pace: null,
            camera: "insert of the phone with the dated message",
            mouth_visibility_required: false,
            duration_hint_seconds: 5,
            function: "insert_evidence",
            audio_role: "silent",
          },
          {
            type: "dialogue",
            speaker: b,
            dialogue: "Three months.",
            emotion: "shame",
            delivery: "flat",
            pace: "slow",
            camera: "close-up",
            mouth_visibility_required: true,
            duration_hint_seconds: d,
            function: "accusation_cu",
            audio_role: "onscreen",
          },
          {
            type: "reaction",
            speaker: a,
            dialogue: null,
            emotion: "the number lands",
            delivery: null,
            pace: null,
            camera: "close-up, the line lands",
            mouth_visibility_required: false,
            duration_hint_seconds: 2.5,
            function: "reaction",
            audio_role: "silent",
            silence_license: "post_nuke",
            speaker_on_camera: a,
          },
          {
            type: "dialogue",
            speaker: b,
            dialogue: "Please.",
            emotion: "pleading",
            delivery: "too familiar",
            pace: "medium",
            camera: "medium close-up",
            mouth_visibility_required: true,
            duration_hint_seconds: 6,
            function: "accusation_cu",
            audio_role: "onscreen",
          },
          {
            type: "dialogue",
            speaker: a,
            dialogue: "Don't say my name.",
            emotion: "cold",
            delivery: "a door closing",
            pace: "slow",
            camera: "medium close-up",
            mouth_visibility_required: true,
            duration_hint_seconds: 6,
            function: "slap_peak",
            audio_role: "onscreen",
            hero: true,
          },
          {
            type: "hero",
            speaker: a,
            dialogue: "Get out.",
            emotion: "final",
            delivery: "quiet",
            pace: "slow",
            camera: "doorway as the elevator chimes",
            mouth_visibility_required: true,
            duration_hint_seconds: 6,
            function: "doorway_reveal",
            audio_role: "onscreen",
          },
          {
            type: "hero",
            speaker: a,
            dialogue: "Who is she?",
            emotion: "unresolved",
            delivery: "cut before the answer",
            pace: "slow",
            camera: "freeze on her face as the doors open",
            mouth_visibility_required: true,
            duration_hint_seconds: 5,
            function: "button_cu",
            audio_role: "onscreen",
          },
        ],
      },
    ],
  };
}
