import { useState } from "react";
import { Badge } from "@/components/base/badges/badges";
import { Button } from "@/components/base/buttons/button";
import { Input } from "@/components/base/input/input";
import { NewActorForm } from "@/components/drama/actor-form.tsx";
import { CastCardSkeleton } from "@/components/drama/cast-card.tsx";
import { Poster } from "@/components/drama/poster.tsx";
import { LoadError } from "@/components/drama/skeleton.tsx";
import { studio, type Actor, type CastSlot } from "@/lib/api.ts";
import { useStudio } from "@/lib/use-studio.ts";
import { cx } from "@/utils/cx";

/**
 * The cast sheet for one show: every part, who plays it, and the controls to
 * change that. Works before the story is written (the buyer names the parts) and
 * after (the parts come from the story). A part nobody claims is written and
 * generated by the run, and the face it gets joins the account's catalog, so the
 * next show can cast it again.
 */
export function CastSheet({ seriesId }: { seriesId: string }) {
  const { data, error, reload } = useStudio(`cast:${seriesId}`, () => studio.seriesCast(seriesId), [seriesId]);
  /** Slot id being recast, "new" for an added part, or null. */
  const [open, setOpen] = useState<string | null>(null);
  const [addRole, setAddRole] = useState("");
  const [busy, setBusy] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  if (error && !data) return <LoadError message={error} onRetry={() => void reload()} />;
  if (!data) {
    return (
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {Array.from({ length: 3 }).map((_, index) => (
          <CastCardSkeleton key={index} />
        ))}
      </div>
    );
  }

  const cast = async (roleName: string, actorId: string | null, characterId?: string) => {
    setBusy(true);
    setSaveError(null);
    try {
      await studio.castRole(seriesId, { role_name: roleName, actor_id: actorId, character_id: characterId });
      setOpen(null);
      setAddRole("");
      await reload();
    } catch (caught) {
      setSaveError(caught instanceof Error ? caught.message : "Could not save the cast.");
    } finally {
      setBusy(false);
    }
  };

  const drop = async (slot: CastSlot) => {
    setBusy(true);
    setSaveError(null);
    try {
      await studio.uncastRole(seriesId, slot.id);
      setOpen(null);
      await reload();
    } catch (caught) {
      setSaveError(caught instanceof Error ? caught.message : "Could not remove this part.");
    } finally {
      setBusy(false);
    }
  };

  const nameTaken = data.items.some((slot) => slot.role_name.trim().toLowerCase() === addRole.trim().toLowerCase());

  return (
    <div className="space-y-6">
      <div className="max-w-2xl">
        <p className="text-sm text-secondary">
          {data.story_written
            ? "Every part in this show. Cast a face from your catalog, or leave a part to be written for you."
            : "Cast anyone you like before the show is written. The story is built around the parts you name here, and every part you leave alone is written and cast for you."}
        </p>
      </div>

      {saveError ? <p className="text-sm text-error-primary">{saveError}</p> : null}

      {data.items.length ? (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {data.items.map((slot) => (
            <SlotCard
              key={slot.id}
              slot={slot}
              busy={busy}
              isOpen={open === slot.id}
              onOpen={() => setOpen(open === slot.id ? null : slot.id)}
              onRemove={() => void drop(slot)}
            >
              <ActorPicker
                seriesId={seriesId}
                roster={data.roster}
                selected={slot.actor_id}
                busy={busy}
                onPick={(actorId) => void cast(slot.role_name, actorId, slot.character_id ?? undefined)}
                onCreated={(actor) => void cast(slot.role_name, actor.id, slot.character_id ?? undefined)}
              />
            </SlotCard>
          ))}
        </div>
      ) : null}

      {data.unclaimed.length ? (
        <section>
          <h3 className="text-sm font-semibold text-tertiary">Parts the story wrote</h3>
          <div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {data.unclaimed.map((role) => (
              <div key={role.id} className="overflow-hidden rounded-xl border border-secondary bg-primary">
                <Poster src={role.still_url} title={role.still_url ? undefined : role.name} chip="Written for you" ratio="34" />
                <div className="p-4">
                  <div className="flex items-start justify-between gap-2">
                    <div className="text-lg font-semibold">{role.name}</div>
                    <Badge type="pill-color" color={role.locked ? "success" : "gray"} size="sm">
                      {role.locked ? "Ready" : "Casting"}
                    </Badge>
                  </div>
                  {role.description ? (
                    <p className="mt-2 line-clamp-3 text-sm text-tertiary">{role.description}</p>
                  ) : null}
                  {role.locked ? (
                    <p className="mt-3 text-sm text-tertiary">
                      This part already shot. Its face stays the same for the rest of the show.
                    </p>
                  ) : (
                    <div className="mt-3">
                      {open === role.id ? (
                        <ActorPicker
                          seriesId={seriesId}
                          roster={data.roster}
                          selected={null}
                          busy={busy}
                          onPick={(actorId) => void cast(role.name, actorId, role.id)}
                          onCreated={(actor) => void cast(role.name, actor.id, role.id)}
                        />
                      ) : (
                        <Button color="secondary" size="sm" onClick={() => setOpen(role.id)}>
                          Cast this part
                        </Button>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      {data.items.length === 0 && data.unclaimed.length === 0 ? (
        <div className="rounded-xl border border-secondary bg-primary p-6">
          <h3 className="text-lg font-semibold">Nobody is cast yet</h3>
          <p className="mt-2 max-w-xl text-sm text-secondary">
            Name a part and pick who plays it. You can be in your own show: add yourself from a photo and that face is
            reusable on every show after this one. Leave this empty and the whole cast is written for you.
          </p>
        </div>
      ) : null}

      <section className="rounded-xl border border-secondary bg-primary p-5">
        <h3 className="text-md font-semibold">Add a part</h3>
        <p className="mt-1 max-w-xl text-sm text-tertiary">
          {data.story_written
            ? "A part you add here is cast now and written into the episodes still to come."
            : "The story will use this name for one of its speaking roles."}
        </p>
        <div className="mt-4 flex max-w-md flex-col gap-3">
          <Input
            label="Part"
            value={addRole}
            onChange={setAddRole}
            placeholder="Yacine"
            isInvalid={Boolean(addRole.trim()) && nameTaken}
            hint={addRole.trim() && nameTaken ? "That part is already on the sheet." : undefined}
          />
          {open === "new" ? (
            <ActorPicker
              seriesId={seriesId}
              roster={data.roster}
              selected={null}
              busy={busy}
              onPick={(actorId) => void cast(addRole, actorId)}
              onCreated={(actor) => void cast(addRole, actor.id)}
            />
          ) : (
            <div>
              <Button
                color="secondary"
                size="sm"
                isDisabled={!addRole.trim() || nameTaken || busy}
                onClick={() => setOpen("new")}
              >
                Choose who plays it
              </Button>
            </div>
          )}
        </div>
      </section>
    </div>
  );
}

function SlotCard({
  slot,
  busy,
  isOpen,
  onOpen,
  onRemove,
  children,
}: {
  slot: CastSlot;
  busy: boolean;
  isOpen: boolean;
  onOpen: () => void;
  onRemove: () => void;
  children: React.ReactNode;
}) {
  const still = slot.character_still_url ?? slot.actor_still_url;
  return (
    <div className="overflow-hidden rounded-xl border border-secondary bg-primary">
      <Poster
        src={still}
        title={still ? undefined : slot.role_name}
        chip={still ? undefined : slot.mode === "actor" ? "Casting" : "Written for you"}
        ratio="34"
      />
      <div className="p-4">
        <div className="flex items-start justify-between gap-2">
          <div className="text-lg font-semibold">{slot.role_name}</div>
          {slot.locked ? (
            <Badge type="pill-color" color="success" size="sm">
              Ready
            </Badge>
          ) : null}
        </div>
        <p className="mt-1 text-sm text-tertiary">
          {slot.actor_name ? (
            <>
              Played by{" "}
              <a href={`/actors/${slot.actor_id}`} className="font-semibold text-primary">
                {slot.actor_name}
              </a>
              {slot.actor_source === "likeness" ? " · from your photo" : ""}
            </>
          ) : (
            "Written and cast for you"
          )}
        </p>
        {slot.character_id ? (
          <a href={`/characters/${slot.character_id}`} className="mt-2 inline-block text-sm font-semibold text-brand-secondary">
            Open the role
          </a>
        ) : null}
        {slot.locked ? (
          <p className="mt-3 text-sm text-tertiary">This part already shot. Its face stays the same.</p>
        ) : (
          <div className="mt-3">
            {isOpen ? (
              children
            ) : (
              <div className="flex gap-2">
                <Button color="secondary" size="sm" onClick={onOpen} isDisabled={busy}>
                  {slot.actor_name ? "Recast" : "Choose a face"}
                </Button>
                <Button color="tertiary" size="sm" onClick={onRemove} isDisabled={busy}>
                  Remove
                </Button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Pick a face from the catalog, hand the part to the writer, or add someone new
 * from a photo without leaving the cast sheet.
 */
function ActorPicker({
  seriesId,
  roster,
  selected,
  busy,
  onPick,
  onCreated,
}: {
  seriesId: string;
  roster: Actor[];
  selected: string | null;
  busy: boolean;
  onPick: (actorId: string | null) => void;
  onCreated: (actor: Actor) => void;
}) {
  const [adding, setAdding] = useState(false);
  const [filter, setFilter] = useState("");

  if (adding) {
    return (
      <div className="rounded-lg bg-secondary p-4">
        <NewActorForm
          compact
          seriesId={seriesId}
          onDone={(actor) => {
            // Close the form as soon as the face exists; the sheet takes over the
            // busy state while it saves the part.
            setAdding(false);
            onCreated(actor);
          }}
          onCancel={() => setAdding(false)}
        />
      </div>
    );
  }

  const needle = filter.trim().toLowerCase();
  const shown = needle
    ? roster.filter(
        (actor) =>
          actor.name.toLowerCase().includes(needle) ||
          actor.tags.some((tag) => tag.toLowerCase().includes(needle)) ||
          actor.shows.some((show) => show.toLowerCase().includes(needle)),
      )
    : roster;

  return (
    <div className="space-y-3">
      {roster.length > 6 ? (
        <Input aria-label="Find an actor" value={filter} onChange={setFilter} placeholder="Find by name, tag, or show" />
      ) : null}
      {shown.length ? (
        <ul className="grid grid-cols-3 gap-2">
          {shown.map((actor) => (
            <li key={actor.id}>
              <button
                type="button"
                disabled={busy}
                onClick={() => onPick(actor.id)}
                className={cx(
                  "block w-full cursor-pointer overflow-hidden rounded-lg text-left ring-1 ring-inset transition disabled:cursor-not-allowed disabled:opacity-60",
                  actor.id === selected ? "ring-2 ring-brand" : "ring-secondary hover:ring-brand",
                )}
              >
                <Poster src={actor.still_url} title={actor.still_url ? undefined : actor.name} ratio="34" />
                <span className="block truncate px-2 py-1.5 text-xs font-semibold text-primary">{actor.name}</span>
              </button>
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-sm text-tertiary">
          {roster.length ? "No face matches that." : "Your catalog is empty. Add someone to start it."}
        </p>
      )}
      <div className="flex flex-wrap gap-2">
        <Button color="secondary" size="sm" onClick={() => setAdding(true)} isDisabled={busy}>
          Add someone new
        </Button>
        <Button color="tertiary" size="sm" onClick={() => onPick(null)} isDisabled={busy}>
          Let the writer cast it
        </Button>
      </div>
    </div>
  );
}
