-- Production design: locations and props as their own things, separate from cast.
--
-- An actor is a face we reuse across shows. A location is an empty set we shoot
-- from several angles. A prop is an object alone on a surface. All three were
-- already generated by the engine, but only actors had a table, so only actors
-- could be seen, named, approved, or regenerated by the buyer.
--
-- The plate id is also written into series.location_refs keyed by name, and the
-- prop still is stored with the engine's own prop-bible metadata key, so the
-- shoot picks these up with no extra wiring.

create table if not exists public.series_locations (
  id uuid primary key default gen_random_uuid(),
  series_id uuid not null references public.series (id) on delete cascade,
  name text not null,
  note text not null default '',
  -- slate: from the brief. buyer: typed by hand. story: written by analyze.
  origin text not null default 'slate',
  position int not null default 0,
  plate_asset_id uuid references public.assets (id) on delete set null,
  -- Vision note from the plate; every close-up in this room carries it.
  lighting_lock text,
  status text not null default 'planned',
  -- A location that has already been shot keeps its plate.
  locked boolean not null default false,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint series_locations_status_check
    check (status in ('planned', 'building', 'ready', 'failed')),
  constraint series_locations_origin_check
    check (origin in ('slate', 'buyer', 'story'))
);

create unique index if not exists series_locations_name_key
  on public.series_locations (series_id, lower(name));
create index if not exists series_locations_series_idx on public.series_locations (series_id);

create table if not exists public.series_props (
  id uuid primary key default gen_random_uuid(),
  series_id uuid not null references public.series (id) on delete cascade,
  name text not null,
  note text not null default '',
  -- cast_device: a slot the cast sheet refused to cast, because it is an object.
  origin text not null default 'slate',
  position int not null default 0,
  still_asset_id uuid references public.assets (id) on delete set null,
  -- The engine's cached prop kinds (letter, phone, contract, watch, carrier).
  kind text,
  -- sealed / open / broken: the same object in a different state.
  state text,
  status text not null default 'planned',
  locked boolean not null default false,
  error text,
  -- The cast slot this object came from, so the two screens stay in step.
  cast_slot_id uuid references public.series_cast (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint series_props_status_check
    check (status in ('planned', 'building', 'ready', 'failed')),
  constraint series_props_origin_check
    check (origin in ('slate', 'buyer', 'story', 'cast_device'))
);

create unique index if not exists series_props_name_key
  on public.series_props (series_id, lower(name));
create index if not exists series_props_series_idx on public.series_props (series_id);

alter table public.series_locations enable row level security;
alter table public.series_locations force row level security;
alter table public.series_props enable row level security;
alter table public.series_props force row level security;

drop policy if exists series_locations_owner on public.series_locations;
create policy series_locations_owner on public.series_locations
  for all to authenticated
  using ((select private.owns_series(series_id)))
  with check ((select private.owns_series(series_id)));

drop policy if exists series_props_owner on public.series_props;
create policy series_props_owner on public.series_props
  for all to authenticated
  using ((select private.owns_series(series_id)))
  with check ((select private.owns_series(series_id)));

-- The design tab watches these while plates and stills are generated.
alter table public.series_locations replica identity full;
alter table public.series_props replica identity full;

do $$
begin
  begin
    alter publication supabase_realtime add table public.series_locations;
  exception
    when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.series_props;
  exception
    when duplicate_object then null;
  end;
end $$;

-- Backfill: a show whose locations were already locked keeps those plates, so
-- the new screen opens with its real rooms instead of an empty slate.
insert into public.series_locations (series_id, name, origin, position, plate_asset_id, status, locked)
select
  s.id,
  ref.key,
  'story',
  (row_number() over (partition by s.id order by ref.key) - 1)::int,
  nullif(ref.value, '')::uuid,
  'ready',
  true
from public.series s
cross join lateral jsonb_each_text(coalesce(s.location_refs, '{}'::jsonb)) as ref(key, value)
where coalesce(ref.value, '') <> ''
on conflict do nothing;
